swagger: "2.0"
info:
  version: "1.0.0"
  title: "Movie API"
  description: "API documentation for managing movies"
basePath: "/"
tags:
  - name: "Health"
    description: "Endpoints for health check"
  - name: "Movies"
    description: "Endpoints for managing movies"
paths:
  /health:
    get:
      tags:
        - "Health"
      summary: "Health Check API"
      description: "Check the health status of the API."
      responses:
        200:
          description: "Success"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                description: "Status of the API"
                example: "OK"
